name: stock-forecasting

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn

  - statsmodels

  - pyyaml
  - tqdm
  - joblib

  - pip
  - pip:
      - yfinance>=0.2.40
      - lightgbm>=4.0.0
      - tensorflow>=2.13
